
production:
  adapter: postgresql
  database: autocompl_prod
  encoding: unicode
  pool: 5
  host: localhost
  username: deploy
  password: 12108484

development:
  database: autocompl
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: dbuser
  password: 12108484